### ISSUE TITLE
Raspberry Pi pico tensor flow.

### ISSUE THREAD

**Issue by develone** [advaitjain/tflite-micro-sparkfun-edge-examples#61]
On 08/29/22 I created my src files with the following command.python3 tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py \
  -e hello_world \
  -e micro_speech \
  -e magic_wand \
  -e person_detection \
  /tmp/tflm-tree

My repo https://github.com/develone/pico-tflmicro-090222 now provides a working hello_world..
-rw-r--r-- 1 devel devel 1781138 Sep  4 09:02 libpico-tflmicro.a 
This uses pico-sdk https://github.com/develone/pico-sdk 1.4.0

What is my next step to get tensorflow for the Raspberry Pi Pico.
I did a pull request on https://github.com/raspberrypi/pico-tflmicro/pulls on an outdated build 
https://github.com/raspberrypi/pico-tflmicro.
Is there a pico teneorflow some where on github?

**Comment by develone** [comment]
I also have a Raspberry Pi O/S 64 bit hello_world example working with the same repo https://github.com/develone/pico-tflmicro-090222.  -rw-r--r-- 1 devel devel 1781062 Sep  5 12:54 libpico-tflmicro.a
These are the steps I used to build the hello_world
   git clone git@github.com:develone/pico-tflmicro-090222.git
    
    cd my-pico-tflmicro-090222
    
    git clone git@github.com:develone/pico-sdk.git
    
    cd pico-sdk
    
    git submodule update --init
    
    cd ../
    
    mkdir build
    
    Created a top level CMakeLists.txt file.
    cd build
    
    export PICO_SDK_PATH=../pico-sdk/
    
    cmake -DPICO_BOARD=pico ..
    
    make

    openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg -c "program examples/hello_world/hello_world.elf verify reset exit"

**Comment by advaitjain** [comment]
The current GitHub repo is only for demonstration purposes and not actively maintained. Can I request that you ask this question on the TFLM repo at https://github.com/tensorflow/tflite-micro?

I can answer there in my capacity as the engineering lead for the TFLM team
